#!/data/data/com.termux/files/usr/bin/bash

videodir="${VICOR_VIDEO_DIR:-/storage/0123-4567/DCIM/Camera}"
outputdir="${VICOR_OUTPUT_DIR:-${HOME}/vicor/data}"
maxsize="${VICOR_MAX_SIZE:-640}"
suffix="${VICOR_FILE_SUFFIX:-mp4}"

function is_termux() {
    command -v termux-wake-lock > /dev/null 2>&1
}

cd "${videodir}"
ls *.${suffix}

for file in *.${suffix}; do
    history -s "${file}"
done

read -e -p '> ' file
if [ -z "${file}" ]; then
    last="$(ls *.${suffix} |tail -n 1)"
    read -e -p '> ' -i "${last}" file
fi

if [ ! -e "${file}" ]; then
    echo 'Bailing out' >&2
    exit 1
fi

outfile="${outputdir}/$(basename "${file}" .${suffix}).${suffix}"

while true; do
    read -p "[n]ormal [s]mall " -n 1 ans
    echo

    case "${ans}" in
        n) break ;;
        s) break ;;
    esac
done

if is_termux; then
    termux-wake-lock
    trap termux-wake-unlock EXIT
fi

if [[ "$ans" == "s" ]] ; then
    ffmpeg -i "${file}" \
    -acodec copy \
    -filter:v scale="w=(trunc(min(a*$maxsize\,$maxsize)/2)*2):h=(trunc(min($maxsize/a\,$maxsize)/2)*2)" \
    -c:v libx264 \
    -profile:v high \
    -preset medium \
    -crf 23 \
    "${outfile}"
elif [[ "$ans" == "n" ]] ; then
    ffmpeg -i "${file}" \
    -acodec copy \
    -vcodec libx264 \
    -profile:v high \
    "${outfile}"
else
    exit 1
fi

if is_termux; then
    termux-vibrate
    termux-wake-unlock
    trap - EXIT
    open_command='termux-open'
    send_command='termux-share -a send'
else
    open_command='xdg-open'
    send_command='xdg-email --attach'
fi

echo
ls -lh "${outfile}"

while true; do
    read -p "[v]iew [s]end [r]emove [q]uit " -n 1 ans
    echo

    case "${ans}" in
        v) $open_command "${outfile}" ;;
        s) $send_command "${outfile}" ;;
        r) rm "${outfile}"
           break ;;
        q) break ;;
    esac
done
