#!/data/data/com.termux/files/usr/bin/bash

videodir='/storage/0123-4567/DCIM/Camera'
outputdir="${HOME}/vicor/data"
factor=0.375

cd "${videodir}"
ls *.mp4

for file in *.mp4; do
  history -s "${file}"
done

read -e -p '> ' file
if [ -z "${file}" ]; then
  last="$(ls *.mp4 |tail -n 1)"
  read -e -p '> ' -i "${last}" file
fi

if [ ! -e "${file}" ]; then
  echo 'Bailing out' >&2
  exit 1
fi

outfile="${outputdir}/$(basename "${file}" .mp4).mp4"
  
termux-wake-lock

ffmpeg -i "${file}" \
  -filter:v scale="trunc(iw*${factor}/2)*2:trunc(ih*${factor}/2)*2" \
  -codec:a libmp3lame \
  -qscale:a 7 \
  -c:v libx264 \
  -preset medium \
  -crf 23 \
  "${outfile}"

termux-vibrate
termux-wake-unlock
echo

ls -lh "${outfile}"

while true; do
  read -p "[v]iew [s]end [r]emove [quit] " -n 1 ans
  echo

  case "${ans}" in
    v) termux-open "${outfile}" ;;
    s) termux-share -a send "${outfile}" ;;
    r)
      rm "${outfile}"
      break
      ;;
    q) break ;;
  esac
done
